[tool.poetry]
name = "dalpha-homework"
version = "0.1.0"
description = "Dalpha Homework"
authors = ["Dalpha <dalpha@dalpha.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"